version: "3"
services:
  nginx: 
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: daupa
      MONGO_INITDB_ROOT_PASSWORD: mypass
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  mongo-db:












  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: daupa
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: mypass
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_BASICAUTH: false