version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: daupa
      MONGO_INITDB_ROOT_PASSWORD: mypass
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:












  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: daupa
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: mypass
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_BASICAUTH: false